config/routes.rb
Rails.application.routes.draw do
  root to: 'pins#index'
  
  resources :pins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    has_one_attached :image

    validates :title, presence: true
    validates :caption, presence: true, length: { minimum: 5 }
    validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  # GET /pins or /pins.json
  def index
    @q = Pin.ransack(params[:q])
    @pins = @q.result
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :caption, :image)
    end

    def search
      if params[:search].blank?
        redirect_to pins_path and return
      else
        @parameter = params[:search].downcase
        @results = Pins.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: "form-control-file"%>
  </div>

  <div class="field form-group">
    <%= form.label :caption %>
    <%= form.text_area :caption, class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit "zakoncz", class:"btn btn-primary", style: "margin:1%"%>
  </div>
 
<% end %>

app/views/pins/edit.html.erb
<header>

  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>Galeria</strong>
      </a>
    </div>
  </div>
</header>
<body>
    <h1 class="h3 mb-3 py-5 font-weight-normal text-center">Edycja pliku</h1>
    <div class="container">
        <%= render 'form', pin: @pin %>

      
        <%= link_to 'Powrót do storny głównej', pins_path, :class => "btn btn-primary btn-sm" %> 
    </div>
</body>

app/views/pins/index.html.erb
<header>

  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>Galeria</strong>
      </a>

      <%= search_form_for @q do |f| %>

        
        <%= f.search_field :title_cont, placeholder:"Szukaj tytułu..." %>
        <%= f.submit "Szukaj!" %>
               
      <% end %>
      <%= link_to 'Nowy Obraz', new_pin_path, :class => "btn btn-primary btn-sm" %>
    </div>
  </div>
</header>
<p id="notice"><%= notice %></p>



<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @pins.each do |pin| %>
        <div class="col" >
        
        <div class="card shadow-sm">
        <th>Tytuł: </th>
        <%= pin.title %>
        <figure class="figure">
        <%= link_to image_tag(pin.image, id:pin.id, class:"card-img-top", style: "height: 40vh"), pin%>
        </figure>

          <div class="card-body">
          <%= pin.caption %>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to 'Usuń', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-sm" %>
                <%= link_to 'Edytuj', edit_pin_path(pin), :class => "btn btn-primary btn-sm"  %>
              </div>
            </div>
          </div>
        </div>
      </div>
        
         <% end %>
      
    </div>
  </div>
</div>

app/views/pins/new.html.erb
<header>

  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>Galeria</strong>
      </a>
    </div>
  </div>
</header>
<div class="container">
  <%= render 'form', pin: @pin %>
  <%= link_to 'Powrót do storny głównej', pins_path, :class => "btn btn-primary btn-sm" %>
</div>

app/views/pins/show.html.erb
<header>

  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>Galeria</strong>
      </a>
      <%= link_to 'Nowy Obraz', new_pin_path, :class => "btn btn-primary btn-sm" %>
    </div>
  </div>
</header>

<p id="notice"><%= notice %></p>


  <div class="container-fluid">
  
        <%= image_tag(@pin.image, class:"img-fluid") %>
        </br>
        <th>Tytuł: </th>
        <%= @pin.title %>
        </br>
        <th>Opis: </th>
        <%= @pin.caption %>
          </br>
       
            
            <%= link_to 'Powrót do storny głównej', pins_path, :class => "btn btn-primary btn-sm" %>
      </div>
  </div>

    
  
  
   